local setmetatable = setmetatable

local GetLocale = GetLocale

local L = {}

if (GetLocale() == "ruRU") then
    -- Races
    L["Human"] = "Человек"
    L["Dwarf"] = "Дворф"
    L["Night Elf"] = "Ночной эльф"
    L["Gnome"] = "Гном"
    L["Draenei"] = "Дреней"
    L["Orc"] = "Орк"
    L["Undead"] = "Нежить"
    L["Tauren"] = "Таурен"
    L["Troll"] = "Тролль"
    L["Blood Elf"] = "Эльф крови"

    -- Classes
    L["Druid"] = "Друид"
    L["Hunter"] = "Охотник"
    L["Mage"] = "Маг"
    L["Paladin"] = "Паладин"
    L["Priest"] = "Жрец"
    L["Rogue"] = "Разбойник"
    L["Shaman"] = "Шаман"
    L["Warlock"] = "Чернокнижник"
    L["Warrior"] = "Воин"

    -- Specs
    L["Balance"] = "Баланс"
    L["Feral"] = "Сила зверя"
    L["Restoration"] = "Исцеление"
    L["Beast Mastery"] = "Повелитель зверей"
    L["Marksmanship"] = "Стрельба"
    L["Survival"] = "Выживание"
    L["Arcane"] = "Тайная магия"
    L["Fire"] = "Огонь"
    L["Frost"] = "Лед"
    L["Holy"] = "Свет"
    L["Protection"] = "Защита"
    L["Retribution"] = "Возмездие"
    L["Discipline"] = "Послушание"
    L["Shadow"] = "Тьма"
    L["Assassination"] = "Ликвидация"
    L["Combat"] = "Бой"
    L["Subtlety"] = "Скрытность"
    L["Elemental"] = "Cтихии"
    L["Enhancement"] = "Совершенствование"
    L["Affliction"] = "Колдовство"
    L["Demonology"] = "Демонология"
    L["Destruction"] = "Разрушение"
    L["Arms"] = "Оружие"
    L["Fury"] = "Неистовство"

    -- Gladdy.lua
    L["Welcome to Gladdy!"] = "Вас приветствует Gladdy!"
    L["First run has been detected, displaying test frame."] = "Обнаружен первый запуск, показываем тестовое окно."
    L["Valid slash commands are:"] = "Валидные команды:"
    L["If this is not your first run please lock or move the frame to prevent this from happening."] = "Если это не первый запуск, переместите, либо закрепите окно во избежание показа окна."

    -- Frame.lua
    L["Gladdy - drag to move"] = "Gladdy - тащите для перемещения"

    -- Options.lua
    L["Announcements"] = "Оповещения"
    L["Announcement settings"] = "Настройки оповещения"
    L["Auras"] = "Ауры"
    L["Auras settings"] = "Настройки аур"
    L["Castbar"] = "Полоса применения"
    L["Castbar settings"] = "Настройки полосы применения"
    L["Classicon"] = "Иконка класса"
    L["Classicon settings"] = "Настройки иконки класса"
    L["Clicks"] = "Клики"
    L["Clicks settings"] = "Настройки кликов"
    L["Diminishings"] = "Диминишинги"
    L["Diminishings settings"] = "Настройки диминишингов"
    L["Healthbar"] = "Полоса жизней"
    L["Healthbar settings"] = "Настройки полосы жизней"
    L["Highlight"] = "Подсветка"
    L["Highlight settings"] = "Настройки подсветки"
    L["Nameplates"] = "Индикаторы здоровья"
    L["Nameplates settings"] = "Настройки индикаторов здоровья "
    L["Powerbar"] = "Полоса маны"
    L["Powerbar settings"] = "Настройки полосы маны"
    L["Score"] = "Счет"
    L["Score settings"] = "Настройки счета"
    L["Trinket"] = "Тринкет"
    L["Trinket settings"] = "Настройки тринкета"
    L["Reset module"] = "Сбросить настройки"
    L["Reset module to defaults"] = "Сбросить настройки модуля к начальным"
    L["No settings"] = "Нет настроек"
    L["Module has no settings"] = "Модуль не имеет настроек"
    L["General"] = "Основные"
    L["General settings"] = "Основные настройки"
    L["Lock frame"] = "Закрепить фрейм"
    L["Toggle if frame can be moved"] = "Включите, если фрейм можно двигать"
    L["Grow frame upwards"] = "Расти вверх"
    L["If enabled the frame will grow upwards instead of downwards"] = "Если включено, то фрейм будет расти вверх, а не вниз"
    L["Frame scale"] = "Масштаб фрейма"
    L["Scale of the frame"] = "Масштаб фрейма"
    L["Frame padding"] = "Отступы фрейма"
    L["Padding of the frame"] = "Отступы фрейма"
    L["Frame color"] = "Цвет фрейма"
    L["Color of the frame"] = "Цвет фрейма"
    L["Bar width"] = "Ширина полос"
    L["Width of the bars"] = "Ширина полос"
    L["Bottom margin"] = "Нижняя граница полосы"
    L["Margin between each button"] = "Отступ до следующей полосы"

    -- Announcements.lua
    L["RESURRECTING: %s (%s)"] = "ВОСКРЕШАЕТ: %s (%s)"
    L["SPEC DETECTED: %s - %s (%s)"] = "СПЕЦИАЛИЗАЦИЯ ОПРЕДЕЛЕНА: %s - %s (%s)"
    L["LOW HEALTH: %s (%s)"] = "МАЛО ЗДОРОВЬЯ: %s (%s)"
    L["TRINKET USED: %s (%s)"] = "ТРИНКЕТ ИСПОЛЬЗОВАН: %s (%s)"
    L["TRINKET READY: %s (%s)"] = "ТРИНКЕТ ГОТОВ: %s (%s)"
    L["DRINKING: %s (%s)"] = "ПЬЁТ: %s (%s)"
    L["Self"] = "Сам"
    L["Party"] = "Группа"
    L["Raid Warning"] = "Объявление рейду"
    L["Blizzard's Floating Combat Text"] = "Стандартный текст боя"
    L["MikScrollingBattleText"] = "MikScrollingBattleText"
    L["Scrolling Combat Text"] = "Scrolling Combat Text"
    L["Parrot"] = "Parrot"
    L["Drinking"] = "Питьё"
    L["Announces when enemies sit down to drink"] = "Оповещать, когда вражеский игрок начинает пить"
    L["Resurrection"] = "Воскрешение"
    L["Announces when an enemy tries to resurrect a teammate"] = "Оповещать, когда вражеский игрок начинает воскрешать союзника"
    L["New enemies"] = "Новые враги"
    L["Announces when new enemies are discovered"] = "Оповещать о найденных вражеских игроках"
    L["Spec Detection"] = "Обнаружение специализации"
    L["Announces when the spec of an enemy was detected"] = "Оповещать, когда обнаружена специализация вражеского игрока"
    L["Low health"] = "Мало жизней"
    L["Announces when an enemy drops below a certain health threshold"] = "Оповещать, когда уровень здоровья вражеского игрока падает ниже определенного количества"
    L["Low health threshold"] = "Процент малого количества здоровья"
    L["Choose how low an enemy must be before low health is announced"] = "Укажите процент здоровья вражеского игрока, когда нужно показать оповещение"
    L["Trinket used"] = "Использование пвп-тринкета"
    L["Announce when an enemy's trinket is used"] = "Оповещать об использовании пвп-тринкета вражеским игроком"
    L["Trinket ready"] = "Готовность пвп-тринкета"
    L["Announce when an enemy's trinket is ready again"] = "Оповещать, когда пвп-тринкет вражеского игрока готов"
    L["Destination"] = "Вариант оповещений"
    L["Choose how your announcements are displayed"] = "Выберать, как показывать оповещения"

    -- Auras.lua
    L["Font color"] = "Цвет текста"
    L["Color of the text"] = "Цвет текста"
    L["Font size"] = "Размер текста"
    L["Size of the text"] = "Размер текста"

    -- Castbar.lua
    L["Bar height"] = "Высота полосы"
    L["Height of the bar"] = "Высота полосы"
    L["Bar texture"] = "Текстура полосы"
    L["Texture of the bar"] = "Текстура полосы"
    L["Bar color"] = "Цвет полосы"
    L["Color of the cast bar"] = "Цвет полосы применений"
    L["Background color"] = "Цвет фона полосы"
    L["Color of the cast bar background"] = "Цвет фона полосы применений"

    -- Clicks.lua
    L["Action #%d"] = "Действие #%d"
    L["Left Click Enemy 1"] = "Левый клик по цели 1"
    L["Left Click Enemy 2"] = "Левый клик по цели 2"
    L["Left Click Enemy 3"] = "Левый клик по цели 3"
    L["Left Click Enemy 4"] = "Левый клик по цели 4"
    L["Left Click Enemy 5"] = "Левый клик по цели 5"
    L["Right Click Enemy 1"] = "Правый клик по цели 1"
    L["Right Click Enemy 2"] = "Правый клик по цели 2"
    L["Right Click Enemy 3"] = "Правый клик по цели 3"
    L["Right Click Enemy 4"] = "Правый клик по цели 4"
    L["Right Click Enemy 5"] = "Правый клик по цели 5"
    L["Left button"] = "Левая кнопка"
    L["Right button"] = "Правая кнопка"
    L["Middle button"] = "Средняя кнопка"
    L["Button 4"] = "Кнопка 4"
    L["Button 5"] = "Кнопка 5"
    L["None"] = "Не назначено"
    L["CTRL"] = "CTRL"
    L["SHIFT"] = "SHIFT"
    L["ALT"] = "ALT"
    L["Cast Spell"] = "Применить заклинание"
    L["Name"] = "Название"
    L["Select the name of the click option"] = "Выбрать название опции клика"
    L["Button"] = "Кнопка"
    L["Select which mouse button to use"] = "Выбрать кнопку мыши для использования"
    L["Modifier"] = "Модификатор"
    L["Select which modifier to use"] = "Выбрать модификатор для использования"
    L["Action"] = "Действите"
    L["Select what action this mouse button does"] = "Выбрать действие, производимое данной кнопкой мыши"
    L["Spell name / Macro text"] = "Название заклинания / Текст макроса"
    L["Use *name* as unit's name. Like a '/rofl *name*'"] = "Используйте *name* в качестве имени игрока. Например, '/rofl *name*'"
    
    -- Diminishings.lua
    L["DR Cooldown position"] = "Позиция ДР таймеров"
    L["Position of the cooldown icons"] = "Позиция ДР таймеров"
    L["Left"] = "Слева"
    L["Right"] = "Справа"
    L["Icon Size"] = "Размер иконок"
    L["Size of the DR Icons"] = "Размер ДР иконок"

    -- Healthbar.lua
    L["Show the actual health"] = "Показывать текущее здоровье"
    L["Show the actual health on the health bar"] = "Показывать текущее здоровье на полосе жизней"
    L["Show max health"] = "Показывать максимальное здоровье"
    L["Show max health on the health bar"] = "Показывать максимальное здоровье на полосе жизней"
    L["Show health percentage"] = "Показывать здоровье в процентах"
    L["Show health percentage on the health bar"] = "Показывать здоровье в процентах на полосе жизней"

    -- Highlight.lua
    L["Target border color"] = "Цвет контура цели"
    L["Color of the selected targets border"] = "Цвет контура цели"
    L["Focus border color"] = "Цвет контура фокуса"
    L["Color of the focus border"] = "Цвет контура фокуса"
    L["Raid leader border color"] = "Цвет контура цели рейд лидера"
    L["Color of the raid leader border"] = "Цвет контура цели рейд лидера"
    L["Highlight target"] = "Подсвечивать цель"
    L["Toggle if the selected target should be highlighted"] = "Включите, если необходима подсветка цели"
    L["Show border around target"] = "Показывать контур вокруг цели"
    L["Toggle if a border should be shown around the selected target"] = "Включите, если необходимо показывать контур вокруг цели"
    L["Show border around focus"] = "Показывать контур вокруг фокуса"
    L["Toggle of a border should be shown around the current focus"] = "Включите, если необходимо показывать контур вокруг фокуса"
    L["Show border around raid leader"] = "Показывать контур вокруг цели рейд лидера"
    L["Toggle if a border should be shown around the raid leader"] = "Включите, если необходимо показывать контур вокруг цели рейд лидера"

    -- Powerbar.lua
    L["Show the actual power"] = "Показывать текущую ману"
    L["Show the actual power on the power bar"] = "Показывать текущую ману на полосе маны"
    L["Show max power"] = "Показывать максимальную ману"
    L["Show max power on the power bar"] = "Показывать максимальную ману на полосе маны"
    L["Show power percentage"] = "Показывать ману в процентах"
    L["Show power percentage on the power bar"] = "Показывать ману в процентах на полосе маны"

    -- Trinket.lua
    L["No cooldown count (OmniCC)"] = "Не показывать кулдаун (OmniCC)"
    L["Disable cooldown timers by addons (reload UI to take effect)"] = "Отключить таймер кулдаунов для аддонов (необходима перезагрузка интерфейса)"
end

-- Superhack allowing use key as value if not present in table
LibStub("Gladdy").L = setmetatable(L, {
    __index = function(t, k)
        return k
    end
})